/**
 * The `.covdbg.yaml` the editor writes when a folder has none. It names no source files: with no
 * `files.include`, covdbg counts every file the target's debug info names, less the Windows SDK,
 * the MSVC toolchain and CRT/STL sources and vendored dependencies excluded here.
 */
export function buildStarterConfig(): string {
    return [
        "# Coverage settings for covdbg",
        "# Format version: 1",
        "",
        "version: 1",
        'source_root: "."',
        "coverage:",
        "  default:",
        "    files:",
        "      # Every source file the target's debug info (PDB) names is counted, except those",
        "      # excluded below. To count only some, list them under 'include':",
        "      #",
        "      #   include:",
        '      #     - "src/**/*.cpp"',
        '      #     - "src/**/*.h"',
        "      #",
        "      # The patterns are glob-style:",
        "      #   - '*'  matches any characters within a single path segment (no directory separators)",
        "      #   - '**' matches across directory boundaries (recursive)",
        "",
        "      # Exclude specific files or directories from the report.",
        "      # Exclude rules always take precedence over include rules.",
        "      exclude:",
        "        # =====================================================================",
        "        # Windows SDK and Universal CRT (installed paths)",
        '        # "C:/Program Files*/Windows Kits/**"',
        "        # =====================================================================",
        '        - "**/Windows Kits/**"',
        "",
        "        # =====================================================================",
        "        # MSVC Toolchain (installed paths)",
        '        # "C:/Program Files*/Microsoft Visual Studio/**/VC/Tools/**"',
        "        # =====================================================================",
        '        - "**/VC/Tools/MSVC/**"',
        "",
        "        # =====================================================================",
        "        # MSVC CRT/STL Source (build server paths from PDBs)",
        "        # These patterns match paths embedded in Microsoft's pre-built binaries",
        "        # from their internal build systems (D:\\a\\_work\\1\\s\\src\\...)",
        "        # =====================================================================",
        '        - "**/vctools/crt/**"           # CRT runtime, startup, vcruntime',
        '        - "**/VCCRT/**"                 # vcruntime headers, named by a relative path',
        '        - "**/vctools/langapi/**"       # Language API (undname, etc.)',
        '        - "**/stl/inc/**"               # STL headers',
        '        - "**/stl/src/**"               # STL source',
        "",
        "        # =====================================================================",
        "        # Universal CRT (UCRT) - minkernel paths from Windows PDBs",
        "        # =====================================================================",
        '        - "**/minkernel/crts/ucrt/**"   # UCRT implementation',
        '        - "**/minkernel/crts/crtw32/**" # Legacy CRT components',
        "",
        "        # =====================================================================",
        "        # Windows SDK internals (onecore paths from Windows PDBs)",
        "        # =====================================================================",
        '        - "**/onecore/**"               # OneCore SDK internals',
        "",
        "        # =====================================================================",
        "        # External SDK includes embedded in PDBs",
        "        # =====================================================================",
        '        - "**/ExternalAPIs/**"          # External API headers',
        '        - "**/binaries/amd64ret/inc/**" # Binary distribution includes',
        "",
        "        # =====================================================================",
        "        # Dependencies (CMake FetchContent, vendored code)",
        "        # =====================================================================",
        '        - "build/**/_deps/**"',
        '        - "third_party/**"',
        '        - "external/**"',
        '        - "vendor/**"',
        "",
        "    functions:",
        "      # Control which functions are included in function-level coverage.",
        "      #",
        "      # Patterns can be fully qualified names (e.g. Namespace::Class::Method) or",
        "      # wildcard expressions using '*'.",
        "      include:",
        '        - "*"  # Include all functions by default',
        "",
        "      # Exclude specific functions (or patterns) from function-level coverage.",
        "      # These are compiler-generated or runtime functions that add noise.",
        "      exclude:",
        "        # MSVC empty global delete (generated by compiler)",
        '        - "__empty_global_delete"',
        "",
        "        # CRT startup/initialization functions",
        '        - "__scrt_*"',
        '        - "_RTC_*"',
        '        - "__security_*"',
        '        - "__GSHandler*"',
        "",
    ].join("\n");
}
